package com.swipeapp.network

internal object Api {

    internal object Url {
        const val PRODUCT_LIST = "api/public/get"

    }

    internal object Path {

        const val ID = "id"
        const val Mode = "mode"
        const val COMMENT_ID = "commentId"
        const val BOOKMARK_ID = "bookmarkId"
        const val CURRENCY = "currency"
        const val USER_ID = "userId"
        const val DEVICE_ID = "deviceId"
        const val REWARD_ID = "rewardId"
        const val PAGE_TYPE = "page_type"
        const val POST_ID = "post_id"
    }

    internal object Part {

        const val FILE = "files"
        const val USER_MEDIA = "userMedia"
    }

    object Header {

        const val IGNORE_LOG_NAME = "IGNORE_LOG"
        const val REQUIRES_AUTHORIZATION = "Auth: true"
        const val REQUIRES_AUTH_TEMP_TOKEN = "Temp-Token: true"
        const val IGNORE_LOG = "$IGNORE_LOG_NAME: true"
        const val REQUIRES_X_ACCESS_TOKEN = "XToken: true"
        const val REQUIRES_X_LANGUAGE = "X-LANGUAGE: true"

        const val TEMP_TOKEN = "Temp-Token"
        const val AUTHORIZATION = "Auth"
        const val X_ACCESS_TOKEN = "XToken"
        const val USER_AGENT = "User-Agent"
        const val DEVICE_ID = "device-id"
        const val X_LANGUAGE = "X-LANGUAGE"
        const val X_FIREBASE_APP_CHECK = "X-Firebase-AppCheck"
        const val VERSION = "Version"
        const val VERSION_CODE = "Version-Code"
        const val PLATFORM = "platform"
        const val TOKEN = "token"
    }

    internal object Param {
        const val SPAM = "spam"

        const val PARTNER_ID = "partnerId"
        const val REFERRER_USENAME = "referrerUsername"
        const val PARTNER_IDS = "partnerIds"
        const val USER_IDS = "userIds"
        const val IDS = "ids"
        const val _ID = "_id"
        const val ID = "id"
        const val planId = "planId"
        const val CHAT_ID = "chatId"
        const val MESSAGE = "message"
        const val PAGE = "page"
        const val PAGE_LIMIT = "perPage"
        const val LIMIT = "limit"
        const val USER_ID = "userId"
        const val INCLUDE_ADS_GIFT = "includeAdsGift"
        const val AVAILABLE_ON = "availableOn"
        const val SOURCE = "source"
        const val NOT_LIVE_SKIP = "notLiveSkip"
        const val SKIP = "skip"
        const val TIMESTAMP = "timestamp"
        const val NAME = "name"
        const val TOPIC = "topic"
        const val RECIPIENT_ID = "recipientId"
        const val RECIPIENT_IDS = "recipientIds"
        const val ADD_TO_SEAT = "addToSeat"
        const val GROUP_TYPE = "groupType"
        const val PAYLOAD = "payload"
        const val PARENT_MESSAGE_ID = "parentId"
        const val EXT = "ext"
        const val LINK = "link"
        const val ROLE = "role"
        const val MUTE = "mute"
        const val PIN = "pin"
        const val QUEST_ID = "questId"
        const val CLICK_ID = "clickId"
        const val BLOCK_USER_ID = "blockedUserId"
        const val MODE = "mode"
        const val PUB_KEY = "publicKey"
        const val PRIVATE_KEY = "encryptedPrivateKey"
        const val ENCODED_TRANSACTION = "encodedTransaction"
        const val ENCODED_TRANSACTION_FIX = "endocdeTransction"
        const val COINS = "coins"
        const val SORTING = "sorting"
        const val FILTER = "filter"
        const val FROM_USER_ID = "fromUserId"
        const val TO_USER_ID = "toUserId"
        const val TRANSACTION_CASE = "transactionCase"
        const val TYPE = "type"
        const val SELECT = "select"
        const val BOOST_TYPE = "typeOfBoost"
        const val ENTITY_ID = "entityId"
        const val PROMOTION_PLAN_ID = "promotionPlanId"
        const val QUESTION_ANSWERED_BY_USER = "questionAnsweredByUser"
        const val BACKUP_PRIVATE_KEY = "backupEncryptedPrivateKey"
        const val REF = "ref"
        const val RECEIVER_USER_ID = "receiverUserId"
        const val VERSION_CODE = "versionCode"
        const val QUERY = "query"
        const val PACKAGE_NAME = "packageName"
        const val ROOM_ID = "roomId"
        const val COMMENT_ID = "commentId"
        const val ROOM_CATEGORY_ID = "reportCategoryId"
        const val COMMENT_CATEGORY_ID = "commentCategoryId"
        const val DESCRIPTION = "description"
        const val ANNOUNCEMENT = "announcement"
        const val FILE = "file"
        const val SEAT = "seat"
        const val BOOST_VALUE = "boostValue"
        const val COST = "cost"
        const val VALUE = "value"
        const val SEARCH_NEW = "searchNew"
        const val BAN_STATUS = "banned"
        const val PRIVACY = "privacy"
        const val LANGUAGE = "language"
        const val LOCATION = "location"
        const val E_LANGUAGE = "elanguage"
        const val LANGUAGE_VIDEO = "preferredLanguage"
        const val LANG = "lang"
        const val OWNER_ID = "ownerId"
        const val EFFECT_ID = "effectId"
        const val PRODUCT_ID = "productId"
        const val ACQUIRE_TYPE = "acquireType"
        const val ACQUIRE_MODE = "acquireMode"
        const val ASSET_ID = "assetId"
        const val CATEGORY = "category"
        const val PLAN_ID = "planId"
        const val SENDER_USER_ID = "senderUserId"
        const val RECIPIENTS_USER_IDS = "recipientsUserIds"
        const val QUANT = "quant"
        const val TOKEN = "token"
        const val DAYS_TO_EXPIRE = "daysToExpire"
        const val PRODUCT_QUANT = "productQuant"
        const val USER_NAME: String = "userName"
        const val PHOTO: String = "photo"
        const val MESSAGES: String = "messages"
        const val BOOSTED = "boosted"
        const val FOLLOW_USER_ID = "followUserId"
        const val MEMBER_ID = "memberId"
        const val UNBLOCK_USER_ID = "unblockUserId"
        const val POST_ID = "postId"
        const val GENDER = "gender"
        const val ALLOW_CHAT = "allowChat"
        const val ALLOW_TIPPING = "allowTips"
        const val ALLOW_LIKES = "allowLikes"
        const val CATEGORY_ID = "categoryId"
        const val ROOM_ICON_URL = "roomIconUrl"
        const val MEDIA_TYPE = "mediaType"
        const val CATEGORY_NAME = "categoryName"
        const val CATEGORIES = "categories"
        const val LANGUAGES = "languages"
        const val CATEGORY_IDS = "categoryIds"

        const val DEVICE_MODEL = "devicemodel"
        const val COUNTRY = "country"
        const val SERVER_TOKEN = "serverToken"
        const val DEVICE_ID = "deviceID"
        const val PUSH_DEVICE_ID = "deviceId"
        const val UTM_SOURCE = "utmSource"
        const val UTM_Campaign = "utmCampaign"
        const val UTM_Label = "utmLabel"
        const val AFF_ID = "affId"
        const val DEVICE_ID_LOWER_CASE = "deviceId"
        const val VERSION_NAME = "versionName"
        const val PLATFORM = "platform"
        const val DEVICE_BRAND = "deviceBrand"
        const val ANDROID_ID = "androidId"
        const val CREATOR_USER_ID = "creatorUserId"
        const val VOTE_COUNT = "voteCount"
        const val COUNTRY_CODE = "countryCode"
        const val REFRESH = "refresh"
        const val VIDEO_IDS = "video_ids"
        const val HASH_TAG = "hashTag"
        const val HASH_TAG_SUGGESTION = "hashtag"
        const val COUNTER = "counter"
        const val DEVICE_ID_FEED = "deviceId"
        const val FEED_TYPE = "feedType"
        const val IS_SCROLL = "isScroll"
        const val IS_DEEPLINK = "isDeeplink"
        const val VIDEO_DURATION = "videoDuration"
        const val SONG_ID = "songId"
        const val SORT = "sort"
        const val TITLE = "title"
        const val DURATION = "duration"
        const val QUERY_SHORT = "q"
        const val KEY = "key"
        const val REASON = "reason"
        const val ENTITY_TYPE = "entityType"
        const val COMMENT = "comment"
        const val CAPTION = "caption"
        const val SHARE = "share"
        const val STATUS = "status"
        const val PAYMENT_METHOD = "paymentMethod"
        const val META = "meta"
        const val CONTACT = "contact"
        const val DOB = "dob"
        const val USERNAME = "username"
        const val EVENT_TYPE = "event_type"
        const val CLIENT_UUID = "client_event_uuid"
        const val APP_VERSION = "appVersion"
        const val ANALYTIC_USER_ID = "user_id"
        const val ANALYTIC_USER_SESSION_ID = "user_session_id"
        const val ANALYTIC_DEVICE_ID = "device_id"
        const val ANALYTIC_DATA = "data"
        const val MINT_ADDRESS = "mintAddress"
        const val OTP = "otp"
        const val BADGE_LEVEL = "badgeLevel"
        const val BADGE_TYPE = "badgeType"
        const val TAG = "tag"
        const val CONTENT_LANGUAGES = "contentLanguages"
        const val IS_FEATURED = "isFeatured"
        const val CREATED_AT = "created_at"
        const val RECEIVER_PUBLIC_KEY = "receiverPublicKey"
        const val WITHDRAWABLE_TRANSACTION_ID = "withDrawbleTransactionId"
        const val AUCTION_PUBKEY = "auction_pubkey"
        const val AMOUNT = "amount"
        const val GARI_AMOUNT = "gariAmount"
        const val TXN_TYPE = "txn_type"
        const val RECORD_ID = "recordId"
        const val BODY = "body"
        const val ERROR = "error"
        const val CODE = "code"
        const val SECONDARY_KEY = "secondaryKey"
        const val FIREBASE_ID = "firebaseId"
        const val REFERENCE_ID = "referenceId"
        const val POSITION = "position"
        const val ICON = "icon"
        const val IS_SELECTED = "isSelected"
        const val ELANGUAGE = "elanguage"

        const val USER_SPL_TOKEN_OWNER = "user_spl_token_owner"
        const val INSTRUCTION_TYPE = "instruction_type"
        const val START = "start"
        const val ENCODED_TRANSACTION_UNDERLINED = "encoded_transaction"
        const val UUID = "uuid"
        const val TAGGED_USERS_IDS = "taggedUserIds"
        const val IS_COMMENT_TAGGED = "isCommentTagged"
        const val SEARCH_TEXT = "searchText"
        const val IS_NEXT_RECENT = "isNextRecent"
        const val NEW_HASHTAGS = "newHashTags"
        const val HASHTAG_IDS = "hashTagIds"
        const val PARENT_COMMENT_ID = "parentCommentId"
        const val REPLY_COMMENT_ID = "replyCommentId"
        const val IS_REPLY = "isReply"
        const val SEARCH_COMMENT_ID = "searchCommentId"

        const val QUANTITY = "quantity"
        const val REDEEM_VALUE = "redeem_value"
        const val VIDEO_ID = "video_id"
        const val VIDEO_CDN_URL = "video_cdn_url"
        const val THUMBNAIL_CDN_URL = "thumbnail_cdn_url"
        const val USER_PUB_KEY = "user_pubkey"
        const val METADATA = "metadata"
        const val FEES = "fees"
        const val NFT_ID = "nft_id"
        const val SETTINGS = "settings"
        const val USER_UD_UNDERLINED = "user_id"
        const val ONLY_V_NFT = "onlyVNFT"
        const val LISTING_SETTINGS = "listing_settings"
        const val NFT_MINT_PUB_KEY = "nft_mint_pubkey"
        const val FEE_PAYER = "fee_payer"
        const val VERSION = "version"
        const val BIRTH_DATE = "birthDate"
        const val INSTALL_REFERRER = "installReferrer"

        // only for audiorooms v1
        const val TOTAL_SPOKEN = "totalSpoken"
        const val TOTAL_LISTEN = "totalListen"

        // audioRoom Quiz
        const val QUIZ_ID = "quizId"
        const val QUESTION_ID = "questionId"
        const val SELECTED_OPTION = "selectedOption"

        // live polls
        const val QUESTION = "question"
        const val OPTIONS = "options"
        const val OPTION_ID = "optionId"
        const val POLL_ID = "pollId"
        const val TIME_TO_ANSWER = "timeToAnswer"

        const val TRUECALLER_TOKEN = "accessTrueCallerToken"
        const val TRUECALLER_SIGN = "trueCallerSign"

        const val NON_GARI_TRANSACTION_ID = "nonGariTransactionId"
        const val TOKEN_AMOUNT = "tokenAmount"
        const val TRANSACTION_ID = "transactionId"
        const val WITHDRAWAL_ID = "withdrawalId"

        const val START_DATE = "startDate"
        const val END_DATE = "endDate"
        const val DATE = "date"
        const val UID = "uid"

        // Private call
        const val CALL_SESSION_ID = "callSessionId"

        // Rating
        const val RATING = "rating"
        const val REVIEWS = "reviewItems"
        const val ROOM_TYPE = "roomType"
        const val ROOM_SESSION_ID = "sessionId"
        const val PROFILE_ID = "profileId"
        const val NICKNAME = "nickName"

        const val SKIP_REFERRAL = "skipReferral"
        const val REFERRAL_CODE = "referralCode"

        // Circles
        const val CIRCLES_POST_MEDIA_TYPE = "mediaType"
        const val CIRCLES_POST_PRIVACY_STATUS = "privacyStatus"
        const val CIRCLES_POST_CAPTION = "caption"
        const val CIRCLES_POST_CAN_SHARE = "share"
        const val CIRCLES_POST_CAN_COMMENT = "comment"
        const val CIRCLES_POST_IMAGE_URL = "urls"
        const val CIRCLES_POST_s3_REF_ID = "s3RefId"
        const val CIRCLES_UPLOAD_FILE_TYPE = "type"
        const val CIRCLES_UPLOAD_FILES = "files"
        const val CIRCLES_POST_CAPTION_LINKS = "links"
        const val CIRCLES_POST_ID = "postId"
        const val CIRCLES_SORT_RECENT = "RECENT"
        const val CIRCLES_SORT_RELEVANT = "RELEVANT"
    }

    internal object Value {
        const val PLATFORM_ANDROID = "android"
        const val ALL = "all"
        const val RATING_PRIVATE_CALL = "PRIVATE_CALL"
    }
}

object ExposedApi {

    object Url {

        const val GARINET_PATH = "/wallet/solana/forwardApis"
    }
}
